"""changed data type

Revision ID: 898df10f95b3
Revises: 4a7220b8bd0d
Create Date: 2024-04-07 15:30:38.113346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898df10f95b3'
down_revision = '4a7220b8bd0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
